version: '3.8'

services:
  db:
    image: 'postgres:13'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo

  db-test:
    image: 'postgres:13'
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
